openapi: 3.0.0
info:
  version: 1.0.0
  title: Integrador Repasse
  termsOfService: 'https://repasses.com.br/terms/'
  contact:
    email: suporte@repasses.com.br
    url: 'https://repasses.com.br'
  x-logo:
    url: 'https://www.repasses.com.br/wp-content/themes/2018_repasse_site/assets/images/logo-repasse-white.png'
    backgroundColor: "#2B4F83"
  description: >

    Esta é a API para visualização / cadastro de anúncios da plataforma Repasse

    # Introdução

    Esta especificação visa auxiliar programadores a integrarem seus sistemas com a plataforma Repasse.



tags:
  - name: Car
    description: Operações referentes ao cadastro e edição de anúncios
servers:
  - url: 'http://beta.aplicativorepasse.com.br/api'
  - url: 'http://app.repasse/api'
